"""empty message

Revision ID: 9465c0c0b538
Revises: a10df13951e3
Create Date: 2019-03-10 14:15:22.255936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9465c0c0b538'
down_revision = 'a10df13951e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aula', sa.Column('ciclo', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'aula', 'ciclo', ['ciclo'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aula', type_='foreignkey')
    op.drop_column('aula', 'ciclo')
    # ### end Alembic commands ###
