"""empty message

Revision ID: a10df13951e3
Revises: cb246bdef801
Create Date: 2019-03-10 14:07:57.677095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10df13951e3'
down_revision = 'cb246bdef801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciclo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participantes',
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('id_instituicao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao'], ['instituicao.id'], ),
    sa.PrimaryKeyConstraint('id_ciclo', 'id_instituicao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participantes')
    op.drop_table('ciclo')
    # ### end Alembic commands ###
