"""empty message

Revision ID: d373e8c6ea12
Revises: 
Create Date: 2019-01-07 16:36:25.538233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd373e8c6ea12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.Column('ID_URI', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ID_URI'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('apelido', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.Column('ID_URI', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ID_URI'),
    sa.UniqueConstraint('apelido'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dia', sa.Date(), nullable=True),
    sa.Column('horario', sa.String(length=5), nullable=False),
    sa.Column('nivel', sa.String(length=15), nullable=False),
    sa.Column('id_prof', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prof'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presenca',
    sa.Column('id_aula', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['aluno.id'], ),
    sa.ForeignKeyConstraint(['id_aula'], ['aula.id'], ),
    sa.PrimaryKeyConstraint('id_aula', 'id_aluno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presenca')
    op.drop_table('aula')
    op.drop_table('professor')
    op.drop_table('aluno')
    # ### end Alembic commands ###
